export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  authMode: process.env.AUTH_MODE ?? "auto",
  localLoginAdmfull: process.env.LOCAL_LOGIN_ADMFULL ?? "",
  localLoginComercial: process.env.LOCAL_LOGIN_COMERCIAL ?? "",
  localLoginSubcomercial: process.env.LOCAL_LOGIN_SUBCOMERCIAL ?? "",
  localLoginGerencia: process.env.LOCAL_LOGIN_GERENCIA ?? "",
  localLoginDiretoria: process.env.LOCAL_LOGIN_DIRETORIA ?? "",
};
